### ISSUE TITLE
Installation / usage manual available?

### ISSUE THREAD

**Issue by k00ni** [balhoff/arachne#146]
I would like to try out this reasoner, but I have no knowledge about Scala and the mentioned build tools (sbt). Is there an installation manual available? 

If not, could you tell me what to do after building the software? Do I run it as a stand alone CLI or use some jar file?

I found a binary in the latest release (`arachne-1.2.1.tgz`, in `bin` folder). When executing it, an error is raised about missing parameters:

```
./arachne
Constructed reasoner from rules in 0.013s
Exception in thread "main" java.lang.IllegalArgumentException: Parameter 'directory' is not a directory: data
	at org.apache.commons.io.FileUtils.validateListFilesParameters(FileUtils.java:541)
	at org.apache.commons.io.FileUtils.listFiles(FileUtils.java:517)
	at org.apache.commons.io.FileUtils.listFiles(FileUtils.java:689)
	at org.geneontology.rules.cli.Main$.$anonfun$run$10(Main.scala:65)
	at org.geneontology.rules.cli.Main$.time(Main.scala:93)
	at org.geneontology.rules.cli.Main$.run(Main.scala:63)
	at org.geneontology.rules.cli.Main$.run(Main.scala:22)
	at org.backuity.clist.CliMain.$anonfun$runWith$1(CliMain.scala:14)
	at org.backuity.clist.Parser.$anonfun$withCommand$1(Parser.scala:156)
	at org.backuity.clist.Parser.withParsingException(Parser.scala:199)
	at org.backuity.clist.Parser.withCommand(Parser.scala:154)
	at org.backuity.clist.CliMain.runWith(CliMain.scala:14)
	at org.backuity.clist.CliMain.main(CliMain.scala:6)
	at org.geneontology.rules.cli.Main.main(Main.scala)
```

Thanks for any hint in advance.

**Comment by balhoff** [comment]
@k00ni I added a section to the Readme with an example: https://github.com/balhoff/arachne#usage

Does this help? If you download the prebuilt version, you can just unzip it and add the `bin` folder to your path (as I think you figured out).

**Comment by balhoff** [comment]
The expectation is that you have two files: one is the ontology itself and the other is an OWL dataset containing an instance graph making reference to classes and properties in the ontology. The dataset doesn't need an `owl:imports` statement for the ontology. Arachne transforms the ontology into a set of rules which are used to compute Abox inferences for the dataset.

**Comment by k00ni** [comment]
@balhoff thank you for your quick response! The new usage section makes it more clear now. I will try that out.
